travis:
  secure:
    BINSTAR_TOKEN: U2B03l3txUOmYPGX4uGBJN0aVuBw9YOtDoJrNjCJDu/5y4ndjmniq0WoUTgsFVvwqaEbusCA1s2xApBsScYVvtpFSgG43Rf4n6MY/p95WH7hz5yP1PAEQgA20OZtZK/HzIA5nXGxfN6hGlLdqCTC5zABoTy/EaCpSD2QUGTgwo3+uolAlaxHUsDlmSfoCpI54G2hQlnW8xBHeEPlAh2hNaqsE8EbFnQlyVOMvtWB8xY9NJc+Wsi5JopLAFZwlhbpv3tsxyjDD8pq1rY6ZX57A5mHv6Hg9TdulI2edx6+w1+aJbI5kCQeR+V4MX2GMN9lgG9ZGqvCdtJ1/bjYk+q/pwGIDp1P99oj5PGiHyThtuW0Xe0y3TBhUee3ea+XpgDgovl+r4FGv1F1jzQ2ICbQYOu6ghGpmBq0oVcAyizJ1pmqEJDDGybURdOHHILCSZr3hjX8qgDLyj4KBFvtM7riMo9Aqq6iOH9S9GZNgNZUmaBgybr8+PeLBh5OLXN0XhSISu2rciq4nSO85yeeoX6NvogqpdTi5bpnY1EV8FanaGoC5pRo+pIw6HB/kYSTbOA/b/lA82xCXQATf1mGLECqF5QK5hbY49aGV/EbLRdpSvhv2qoFd822vTeU9hsfAWS5KB4k1XwFV7WjWEOukCRsbAgZDeBeNgaHBaq4hQ3Sn34=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
