travis:
  secure:
    BINSTAR_TOKEN: AgEyA6O4WXrUMn8JCNw5DXuOakilMLYXcieYAQU3IRS/2adAN/uDskNqYOHEZg23YWKzxm1SGFb5aJGU0hdLleBYiiu04wlbRBZc6AlV1ieRXoTf9wIe5gg2aEQlLTNOdetQCQRwqprtpANQApfkZtOK4U91A0398jo841jEyWcZdMXyKMRkWS305DlAstA3MY5OzZTnxC4bsYkzLsSwze2b2xvNFZfKtVN6oBTvWU+vO9Xb7PSAM5vjUuxcL31GS6IyMmm6d2xNg2JICU27xOAXY5dTZbmFNuIiPNgqU4sbPB9Pky4Cdn4Uk3bnRpz+C5qT/1CS8j4q+qJ5hIl8ktxdjU7Ocmj8TZMfjw6XzMrS7Q0c/XrY/5MrWyfl2sAWUkr1y92qxXXZsX4jtQqyzlCDpnNzhBVmdCBepTbah2RWnSyBpBSCVpRlMLGvFSN4DKxOJJXEXO6xk8mR+tYj10FI5qzf8Tz1gjL3mPjs6LdBIyo/O8sqbrVakZL7RaOnKKligw+9wrJoUks5IwA7I/KiHyVOO7fUJwAH42HhDgpF5w6S0MmTXN5WEw4d4Ranij8M8BQv4uYLGr2YqbaFAZvocCwlH1+SYCcLbPx0kX+WmkV1uRP4sCR1hThSiUWINavATG4ll+E5XtsoCh+pgkAOpVAdm2znpgkf1XnrEOM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
