travis:
  secure:
    BINSTAR_TOKEN: oqWZ/sBGbmnPvMi0uBeDFCp/UZJuEAi63MDxFW4b8DtoAVbLjW8Dmtjxe72/z/vK5PPE86t2/4xadTNr1cY2kBxhXpLfi4fXxtIhfg8yZaJ6QgCDogsRt8ogHX3h7wqPGZQopbCyTcm/37S0PJsi/U7AJ7gurVWCjJPclb7f1Vig8VgblYCNdz7lqCo14h09iFA0r9P6gtKtcXJQ2e2ul0KWh5EayyhMtEwCTcOVJp3RIDLdYee9xHf/81Y/PdOe3k+ITUkDjW8RbGwYOvyu65pbs53MeYdWdggitIoGJBWElH7cKxjHAcda6y8ckCFdr+WSMVYVSEiIkA52InWXkZTJN7v2h7RwiGaNoyoviyhV9kgFAJWvcIXlR8rSY6v6S+dXuIWzTLU+1ZmtZoY4otZbHybNYOXNAPzBOChLNBv6Txob4Hq8LDmUHmvsXEfFLXqrooSPuLdGJ5qvMxTnWwpSGJpvzyCfo6OoFKxMtF4fmi2ltsS0IHKQSgXm9FdZiVSUZbOfKrdNfQu9BT/XFoGNqc5nYnckzACmLa8mh1+czDFFPeWFZyDrQuWIgpQtwBpCps44cYlGCBfc7HtCbZyDkRJP53Xd1o/bek38oD0+15qZQbSB8bqOMhbzSn/qqHU+AsYnTHwRIdDsZiUQnrXahDeiEmPAjPcbUp3W0OI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
